/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Nov 22, 2010, 4:17:37 AM
 */
package gui;

import gui.aboutUs.AboutUsWindow;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logic.FetchingProcess;
import wordRetrieval.KeywordRetrieval;
import wordRetrieval.WordInfo;

/**
 * Main window of the user comment analyzer application.
 *
 * @author javiersalcedogomez
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Keyword generated list from the word retrieval process.
     */
    private ArrayList<WordInfo[]> _productKeywordList;
    /**
     * Main window unique class instance.
     */
    private static MainWindow _instance;
    /**
     * Panels displayed with the products to compare.
     */
    private ArrayList<ProductPanel> _productPanelList;
    /**
     * Word retrieval manager of the application.
     */
    private KeywordRetrieval _wordRetrieval;
    /**
     * Thread which executes the fetching process.
     */
    private FetchingProcess _fetchingProcess;
    /**
     * Thread which executes the keyword retrieval process.
     */
    private KeywordRetrievalProcess _keywordRetrievalProcess;
    /**
     * Thread which executes the applying filter process.
     */
    private ApplyFilterProcess _appyFilterProcess;

    /**
     * Creates the Main Window of the application.
     */
    public MainWindow() {

        // Initializes the window components.
        initComponents();

        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        setLocation(x, y);

        // Creates the word retrieval manager
        _wordRetrieval = new KeywordRetrieval();

        // Creates the keyword list
        _productKeywordList = new ArrayList<WordInfo[]>();

        // Creates the product panel list
        _productPanelList = new ArrayList<ProductPanel>();
    }

    /**
     * Returns the unique main window class instance.
     * 
     * @return the unique main window class instance.
     */
    public static MainWindow getInstance() {

        if (_instance == null) {
            _instance = new MainWindow();
        }
        return _instance;
    }

    /**
     * Updates the keyword list with the last keyword list generated by the
     * keyword retrieval algorithm.
     */
    public void updatesKeywordList() {
        try {

            // Run the keyword retrieval process
            MainWindow.getInstance().runKeywordRetrieval();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Builds the results panel. Always builds the results panel with the
     * product keyword list.
     */
    public void buildResultsPanel() {

        // Removes all the panels
        _productsPanel.removeAll();

        // Clears the product panel list
        _productPanelList.clear();

        // Builds the results panel
        for (int index = 0; index < _productKeywordList.size(); index++) {

            // Creates the product panel
            ProductPanel productPanel = new ProductPanel(index);

            // Creates a border with the number of the product
            productPanel.setBorder(BorderFactory.createTitledBorder("Product " + (index + 1)));

            // Updates the keyword list to display
            productPanel.setProductList(_productKeywordList.get(index));

            // Adds the product panel to the results panel
            GridBagConstraints constraints = new GridBagConstraints();
            constraints.gridx = index;
            constraints.gridy = 0;
            _productsPanel.add(productPanel, constraints);

            // Updates the product panel list
            _productPanelList.add(productPanel);
        }

        // Validates the changes in the main window
        validate();

        // Repaints the main window
        repaint();
    }

    /**
     * Applies the filter to all the displayed panels.
     */
    public void applyFilter() {


        // Shows the waiting window
        WaitingWindow.getInstance().showWaitingWindow();

        // TODO: Allow to the user to selects the products to apply the filter on


        // Builds the results panel
        for (int index = 0; index < _productKeywordList.size(); index++) {

            try {
                // Rebuilds the keywordlist
                _productKeywordList.set(index, _wordRetrieval.run(_keywordRetrievalFilterTextField.getText()));

            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

            _productPanelList.get(index).setProductList(_productKeywordList.get(index));
        }

        // Validates the changes in the main window
        validate();

        // Repaints the main window
        repaint();


        // Shows the waiting window
        WaitingWindow.getInstance().closeWaitingWindow();
    }

    /**
     * Returns the products panel.
     *
     * @return the products panel.
     */
    public JPanel getProductsPanel() {
        return _productsPanel;
    }

    /**
     * Returns the product panel list.
     *
     * @return the product panel list.
     */
    public ArrayList<ProductPanel> getProductPanelList() {
        return _productPanelList;
    }

    /**
     * Returns the product keyword list.
     *
     * @return the product keyword list.
     */
    public ArrayList<WordInfo[]> getProductKeywordList() {
        return _productKeywordList;
    }

    /**
     * Returns the getting results process thread.
     *
     * @return the getting results process thread.
     */
    public Thread getGettingResultsProcess() {
        return _keywordRetrievalProcess;
    }

    /**
     * Returns the URL product text field text.
     *
     * @return the URL product text field text.
     */
    public String getURLProductText() {
        return _URLProductTextField.getText();
    }

    /**
     * Runs the keyword retrieval algorithm with the specified filter.
     *
     * @throws IOException
     */
    public void runKeywordRetrieval() throws IOException {
        _productKeywordList.add(_wordRetrieval.run(_keywordRetrievalFilterTextField.getText()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        _searchPanel = new javax.swing.JPanel();
        _URLProductPanel = new javax.swing.JPanel();
        _URLProduct = new javax.swing.JLabel();
        _URLProductTextField = new javax.swing.JTextField();
        _buttonPanel = new javax.swing.JPanel();
        _generateResultsButton = new javax.swing.JButton();
        _resultsScrollPane = new javax.swing.JScrollPane();
        _resultsPanel = new javax.swing.JPanel();
        _productsPanel = new javax.swing.JPanel();
        _filterPanel = new javax.swing.JPanel();
        _keywordRetrievalFilterLabel = new javax.swing.JLabel();
        _keywordRetrievalFilterTextField = new javax.swing.JTextField();
        _helpButton = new javax.swing.JButton();
        _applyFilterButton = new javax.swing.JButton();
        _menuBar = new javax.swing.JMenuBar();
        _fileMenu = new javax.swing.JMenu();
        _exitMenuItem = new javax.swing.JMenuItem();
        _helpMenu = new javax.swing.JMenu();
        _aboutUsMenuItem = new javax.swing.JMenuItem();
        _helpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Comment Analyzer");
        setExtendedState(1);
        setResizable(false);

        _searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Configuration"));
        _searchPanel.setLayout(new java.awt.BorderLayout());

        _URLProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("URL Product Configuration"));
        _URLProductPanel.setLayout(new java.awt.GridBagLayout());

        _URLProduct.setText("Type the product URL:");
        _URLProduct.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        _URLProductPanel.add(_URLProduct, gridBagConstraints);

        _URLProductTextField.setPreferredSize(new java.awt.Dimension(14, 25));
        _URLProductTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _URLProductTextFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.9;
        _URLProductPanel.add(_URLProductTextField, gridBagConstraints);

        _searchPanel.add(_URLProductPanel, java.awt.BorderLayout.CENTER);

        _buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        _generateResultsButton.setText("Generate product results");
        _generateResultsButton.setToolTipText("Generates the product keyword list associated to the typed URL");
        _generateResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateResultsButtonActionPerformed(evt);
            }
        });
        _buttonPanel.add(_generateResultsButton);

        _searchPanel.add(_buttonPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(_searchPanel, java.awt.BorderLayout.NORTH);

        _resultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Results panel"));
        _resultsPanel.setLayout(new java.awt.BorderLayout());

        _productsPanel.setLayout(new java.awt.GridBagLayout());
        _resultsPanel.add(_productsPanel, java.awt.BorderLayout.CENTER);

        _filterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("keyword Retrieval Filters "));
        _filterPanel.setLayout(new java.awt.GridBagLayout());

        _keywordRetrievalFilterLabel.setText("Type the keyword retrieval filter: ");
        _keywordRetrievalFilterLabel.setPreferredSize(new java.awt.Dimension(216, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        _filterPanel.add(_keywordRetrievalFilterLabel, gridBagConstraints);

        _keywordRetrievalFilterTextField.setText("[*]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        _filterPanel.add(_keywordRetrievalFilterTextField, gridBagConstraints);

        _helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/images/help.png"))); // NOI18N
        _helpButton.setToolTipText("Displays a help file with the filter usage");
        _helpButton.setContentAreaFilled(false);
        _helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _helpButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        _filterPanel.add(_helpButton, gridBagConstraints);

        _applyFilterButton.setText("Apply Filter");
        _applyFilterButton.setToolTipText("Applies the filter to the selected products");
        _applyFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _applyFilterButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        _filterPanel.add(_applyFilterButton, gridBagConstraints);

        _resultsPanel.add(_filterPanel, java.awt.BorderLayout.NORTH);

        _resultsScrollPane.setViewportView(_resultsPanel);

        getContentPane().add(_resultsScrollPane, java.awt.BorderLayout.CENTER);

        _fileMenu.setText("File");

        _exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        _exitMenuItem.setText("Exit");
        _exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        _fileMenu.add(_exitMenuItem);

        _menuBar.add(_fileMenu);

        _helpMenu.setText("Help");

        _aboutUsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        _aboutUsMenuItem.setText("About us...");
        _aboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _aboutUsMenuItemActionPerformed(evt);
            }
        });
        _helpMenu.add(_aboutUsMenuItem);

        _helpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        _helpMenuItem.setText("Help");
        _helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _helpMenuItemActionPerformed(evt);
            }
        });
        _helpMenu.add(_helpMenuItem);

        _menuBar.add(_helpMenu);

        setJMenuBar(_menuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-975)/2, (screenSize.height-725)/2, 975, 725);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the application.
     *
     * @param evt action event.
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

        // Exits the application
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * Generates the comments.txt file for the URL of the typed product and
     * displays:
     *    - The fetching process in a separate progress window.
     *    - The results in the main window:
     *        - Adds the new generated list with the selected word retrieval
     *        parameters in the new keyword tab.
     *        - Adds a new tab with all the info of the product.
     *
     * @param evt action event.
     */
    private void generateResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateResultsButtonActionPerformed

        if (!_URLProductTextField.getText().matches("")) {

            // The fetching proccess in a separate thread
            _fetchingProcess = new FetchingProcess();

            // The results creation in other different thread
            _keywordRetrievalProcess = new KeywordRetrievalProcess();

            // Starts the fetching process
            _fetchingProcess.start();
        } else {
            JOptionPane.showMessageDialog(this, "You have to type a valid product URL first!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateResultsButtonActionPerformed

    /**
     * About us menu item action listener.
     *
     * @param evt action event.
     */
    private void _aboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__aboutUsMenuItemActionPerformed

        // Shows the about us window
        new AboutUsWindow().setVisible(true);
    }//GEN-LAST:event__aboutUsMenuItemActionPerformed

    /**
     * Help menu item action listener.
     *
     * @param evt action event.
     */
    private void _helpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__helpMenuItemActionPerformed
        // Shows the help file of the application
    }//GEN-LAST:event__helpMenuItemActionPerformed

    /**
     * URL product text field key pressed listener.
     *
     * @param evt action event
     */
    private void _URLProductTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__URLProductTextFieldKeyPressed

        // If the user presses the ENTER 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            _generateResultsButton.doClick();
        }
    }//GEN-LAST:event__URLProductTextFieldKeyPressed

    private void _applyFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__applyFilterButtonActionPerformed

        // Executes the process in a separate Thread
        _appyFilterProcess = new ApplyFilterProcess();

        // Starts the filter
        _appyFilterProcess.start();       
    }//GEN-LAST:event__applyFilterButtonActionPerformed

    private void _helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__helpButtonActionPerformed
        // TODO ARJEN!!!!!!!!

    }//GEN-LAST:event__helpButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _URLProduct;
    private javax.swing.JPanel _URLProductPanel;
    private javax.swing.JTextField _URLProductTextField;
    private javax.swing.JMenuItem _aboutUsMenuItem;
    private javax.swing.JButton _applyFilterButton;
    private javax.swing.JPanel _buttonPanel;
    private javax.swing.JMenuItem _exitMenuItem;
    private javax.swing.JMenu _fileMenu;
    private javax.swing.JPanel _filterPanel;
    private javax.swing.JButton _generateResultsButton;
    private javax.swing.JButton _helpButton;
    private javax.swing.JMenu _helpMenu;
    private javax.swing.JMenuItem _helpMenuItem;
    private javax.swing.JLabel _keywordRetrievalFilterLabel;
    private javax.swing.JTextField _keywordRetrievalFilterTextField;
    private javax.swing.JMenuBar _menuBar;
    private javax.swing.JPanel _productsPanel;
    private javax.swing.JPanel _resultsPanel;
    private javax.swing.JScrollPane _resultsScrollPane;
    private javax.swing.JPanel _searchPanel;
    // End of variables declaration//GEN-END:variables
}
