/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductPanel.java
 *
 * Created on Dec 16, 2010, 7:39:35 PM
 */
package gui.mainWindow;

import gui.productCommentsWindow.ProductCommentsWindow;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import wordRetrieval.WordInfo;

/**
 * Panel which shows the list of keywords related to one product. Also has two
 * buttons to close the product, so it will not be available for further
 * comparissons, or the statistics button to print the results with plots.
 *
 * @author javiersalcedogomez
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Product panel index in the main window.
     */
    private int _index;

    /** 
     * Creates new form ProductPanel.
     */
    public ProductPanel() {

        // Initializes the window components
        initComponents();
    }

    /**
     * Creates a new product panel.
     *
     * @param index product panel index in the main window.
     */
    public ProductPanel(int index) {

        // Initializes the window components
        initComponents();

        _index = index;
    }

        /**
     * Returns the product list which contains the keywords extracted from
     * the user product comments.
     *
     * @return the product list which contains the keywords extracted from
     * the user product comments.
     */
    public JList getProductList() {
        return _productList;
    }

    /**
     * Sets a new value to the product list data.
     *
     * @param keywordList new value to set.
     */
    public void setProductList(final WordInfo[] keywordList) {

        SwingUtilities.invokeLater(new Runnable() {

            public void run() {

                if(keywordList != null && keywordList.length > 0)
                    _productList.setListData(keywordList);
            }
        });
    }

    /**
     * Searches for the keyword in the list and selects it.
     *
     * @param theWord keyword to select.
     */
    public void setSelectedKeyword(final String theWord) {

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                boolean found = false;

                // Searches for the keyword in the list and selects it
                for (int index = 0; index < _productList.getModel().getSize(); index++) {

                    // Gets the element from the list
                    WordInfo wordInfo = (WordInfo) _productList.getModel().getElementAt(index);

                    // If that element is the word
                    if (wordInfo.getTheWord().matches(theWord)) {

                        // Selects it
                        _productList.setSelectedIndex(index);

                        // Keyword found
                        found = true;
                    }
                }

                // If the keyword wasn't found
                if(!found)
                    // Clears the selected index
                    _productList.setSelectedIndex(-1);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        _productScrollPane = new javax.swing.JScrollPane();
        _productList = new javax.swing.JList();
        _buttonPanel = new javax.swing.JPanel();
        _showCommentButton = new javax.swing.JButton();
        _closeButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 425));
        setLayout(new java.awt.GridBagLayout());

        _productScrollPane.setName("_productScrollPane"); // NOI18N
        _productScrollPane.setPreferredSize(new java.awt.Dimension(300, 400));

        _productList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        _productList.setName("_productList"); // NOI18N
        _productList.setVisibleRowCount(-1);
        _productList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                _productListValueChanged(evt);
            }
        });
        _productScrollPane.setViewportView(_productList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(_productScrollPane, gridBagConstraints);

        _buttonPanel.setName("_buttonPanel"); // NOI18N
        _buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        _showCommentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/images/icons/Show.png"))); // NOI18N
        _showCommentButton.setText("Show Comment");
        _showCommentButton.setToolTipText("Shows the comments with the selected keyword highlighted in the comments");
        _showCommentButton.setName("_showCommentButton"); // NOI18N
        _showCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _showCommentButtonActionPerformed(evt);
            }
        });
        _buttonPanel.add(_showCommentButton);

        _closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/resources/images/icons/Close.png"))); // NOI18N
        _closeButton.setText("Close");
        _closeButton.setToolTipText("Closes the product panel list");
        _closeButton.setName("_closeButton"); // NOI18N
        _closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        _buttonPanel.add(_closeButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(_buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Close button action listener. Closes the panel erasing from the 
     * panel list of the main window and updating the main window without it.
     * 
     * @param evt action event.
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        // Removes the product keyword list from the main list
        MainWindow.getInstance().getProductKeywordList().remove(_index);

        if(MainWindow.getInstance().getProductKeywordList().isEmpty())
            MainWindow.getInstance().getApplyFilterButton().setEnabled(false);

        // Builds the results panel again
        MainWindow.getInstance().buildResultsPanel();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * Product list value changed action.
     *
     * Selects in the other list, if any, the same keyword selected in the
     * current list.
     *
     * @param evt list selection event.
     */
    private void _productListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event__productListValueChanged

        // Gets the keyword from the list
        WordInfo wordInfo = (WordInfo) _productList.getSelectedValue();

        // Selects the same keyword in the other lists
        MainWindow.getInstance().selectKeywordInOtherLists(wordInfo.getTheWord());
    }//GEN-LAST:event__productListValueChanged

    /**
     * Show comment button action.
     *
     * Shows a new window with the user comments associated to the current
     * keyword list with the selected keyword in the list highlighted in the
     * new window.
     *
     * @param evt action event.
     */
    private void _showCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__showCommentButtonActionPerformed

        // Displays a window with the comments related to the product and
        // the word selected in the list highlighted
        if (_productList.getSelectedIndex() != -1) {

            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {

                    // Gets the keyword from the list
                    WordInfo wordInfo = (WordInfo) _productList.getSelectedValue();

                    // Displays the product comment window
                    new ProductCommentsWindow(wordInfo.getTheWord(), _index + 1);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "You must select a keyword in the list first", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event__showCommentButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _buttonPanel;
    private javax.swing.JButton _closeButton;
    private javax.swing.JList _productList;
    private javax.swing.JScrollPane _productScrollPane;
    private javax.swing.JButton _showCommentButton;
    // End of variables declaration//GEN-END:variables

}
